[platformio]
default_envs = adafruit_qtpy_esp32s3_nopsram

[env:adafruit_qtpy_esp32s3_nopsram]
platform = espressif32
board = adafruit_qtpy_esp32s3_nopsram
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

; --- Build Flags ---
; These flags force the S3 to route Serial over the native USB CDC port
; so you can see console logs, and enable code-optimization.
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -O2

; --- Library Dependencies ---
lib_deps =
    # Display Libraries
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/Adafruit LiquidCrystal @ ^2.0.4
    Wire

    # Encoder & Hardware Breakout Libraries
    adafruit/Adafruit Seesaw Library @ ^1.7.5
    adafruit/Adafruit BusIO @ ^1.16.1

    # Audio & Spotify Playback Libraries
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.0
    bblanchon/ArduinoJson @ 7.4.3

    # Sinric Pro Smart Home Alexa Trigger Library
    sinricpro/SinricPro @ ^3.2.0

; --- Upload Settings ---
upload_speed = 115200

[env:native]
platform = native
build_src_filter = -<*>